/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./components/Card/About.vue')['default']
    AppCalendar: typeof import('./components/AppCalendar.vue')['default']
    BaseButton: typeof import('./components/core/BaseButton.vue')['default']
    BaseIcon: typeof import('./components/core/BaseIcon.vue')['default']
    BaseInput: typeof import('./components/core/BaseInput.vue')['default']
    BonusHistoryItem: typeof import('./components/Card/BonusHistoryItem.vue')['default']
    Code: typeof import('./components/core/Code.vue')['default']
    CodeInput: typeof import('./components/core/CodeInput.vue')['default']
    DateIndicator: typeof import('./components/Calendar/DateIndicator.vue')['default']
    EssentialLink: typeof import('./components/EssentialLink.vue')['default']
    EventList: typeof import('./components/Calendar/EventList.vue')['default']
    EventType: typeof import('./components/Calendar/EventType.vue')['default']
    ExampleComponent: typeof import('./components/ExampleComponent.vue')['default']
    Fast: typeof import('./components/Card/Fast.vue')['default']
    Footer: typeof import('./components/Layout/Footer.vue')['default']
    Header: typeof import('./components/Layout/Header.vue')['default']
    Index: typeof import('./components/Stories/Index.vue')['default']
    InputCode: typeof import('./components/core/input-code.vue')['default']
    Item: typeof import('./components/Stories/Item.vue')['default']
    Masters: typeof import('./components/Card/Masters.vue')['default']
    MonthDayItem: typeof import('./components/Calendar/MonthDayItem.vue')['default']
    OurServices: typeof import('./components/Card/OurServices.vue')['default']
    Record: typeof import('./components/Card/Record.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Stories: typeof import('./components/Stories/index.vue')['default']
    TabBody: typeof import('./components/core/TabBody.vue')['default']
    TabContent: typeof import('./components/core/TabContent.vue')['default']
    TabItem: typeof import('./components/core/TabItem.vue')['default']
    TabItemList: typeof import('./components/core/TabItemList.vue')['default']
    UpcomingRecord: typeof import('./components/Card/UpcomingRecord.vue')['default']
    WeekDays: typeof import('./components/Calendar/WeekDays.vue')['default']
    Works: typeof import('./components/Card/Works.vue')['default']
  }
}
